import type { SummaryResult } from '../providers';
import { formatCost, formatTokenCount } from '../utils/tokens';
import type { FormatOptions } from './index';

export async function formatGitHub(
  result: SummaryResult,
  options: FormatOptions = {}
): Promise<string> {
  const lines: string[] = [];

  lines.push('## Diff Intent Analysis');
  lines.push('');

  if (result.purpose.length > 0) {
    lines.push('<details open>');
    lines.push('<summary><strong>Purpose</strong></summary>');
    lines.push('');
    for (const item of result.purpose) {
      lines.push(`- ${item}`);
    }
    lines.push('');
    lines.push('</details>');
    lines.push('');
  }

  if (result.changeType.length > 0) {
    lines.push('<details open>');
    lines.push('<summary><strong>Change Type</strong></summary>');
    lines.push('');
    for (const item of result.changeType) {
      lines.push(`- ${item}`);
    }
    lines.push('');
    lines.push('</details>');
    lines.push('');
  }

  if (result.risks.length > 0) {
    lines.push('<details open>');
    lines.push('<summary><strong>Risks</strong></summary>');
    lines.push('');
    for (const item of result.risks) {
      lines.push(`- ${item}`);
    }
    lines.push('');
    lines.push('</details>');
    lines.push('');
  }

  if (result.tests.length > 0) {
    lines.push('<details open>');
    lines.push('<summary><strong>Suggested Tests</strong></summary>');
    lines.push('');
    for (const item of result.tests) {
      lines.push(`- [ ] ${item}`);
    }
    lines.push('');
    lines.push('</details>');
    lines.push('');
  }

  if (options.showCost && result.meta) {
    lines.push('---');
    lines.push('<sub>');
    const parts: string[] = [];
    if (result.meta.tokens) {
      parts.push(`Tokens: ${formatTokenCount(result.meta.tokens)}`);
    }
    if (result.meta.cost !== undefined) {
      parts.push(`Cost: ${formatCost(result.meta.cost)}`);
    }
    if (options.provider || result.meta.model) {
      parts.push(`Provider: ${options.provider || result.meta.model}`);
    }
    lines.push(parts.join(' | '));
    lines.push('</sub>');
  }

  lines.push('');
  lines.push('---');
  lines.push('*Generated by [diff-intent](https://github.com/SyedSibtainRazvi/diff-intent)*');

  return lines.join('\n');
}
